######################################################
##                                                  ##
##              SSB - SlimeWorldManager             ##
##             Developed by Ome_R, grayr0ot         ##
##                                                  ##
######################################################

# The data source to use for the island worlds.
# Choose one of the following types below.
data-source:
  type: 'file'
  # The settings below are only relevant if you use ASP 3
  # File related settings
  file:
    path: 'slime_worlds'
  # MySQL related settings
  mysql:
    url: 'jdbc:mysql://{host}:{port}/{database}?autoReconnect=true&allowMultiQueries=true&useSSL={usessl}'
    host: 127.0.0.1
    port: 3306
    username: ''
    password: ''
    database: ''
    useSSL: false
  # MongoDB related settings
  mongodb:
    url: 'mongodb://{username}:{password}@{host}:{port}/'
    host: 127.0.0.1
    port: 27017
    auth: ''
    username: ''
    password: ''
    database: ''
    collection: ''
  # API related settings
  api:
    username: ''
    token: ''
    url: ''
    ignore-ssl-certificate: false

# The delay until unloading a world from its last access time, in seconds.
# If you don't want to have any delay, set it to 0 or below.
unload-delay: 600

# Whether to teleport players to their island when they log in
teleport-to-island: true